### PR TITLE
ggstatsplot as extension of ggplot2

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by Emaasit** [comment]
@IndrajeetPatil the config.yml file does not play well with extra white spaces. Could you please delete those spaces and push into this reverted branch? Thanks.

**Comment by IndrajeetPatil** [comment]
I have no idea where the extra white spaces are. The error tells me that there is an error on line no. 1. But the line no. 1 in my forked yml file is the same as the one in the master branch. Do you know where the extra spaces are here in the`ggstatsplot` portion?
https://github.com/IndrajeetPatil/gallery/blob/gh-pages/_config.yml

**Comment by Emaasit** [comment]
screen shot 2018-03-27 at 10 12 09 pm

My sublime text editor shows that `ggstatsplot` is not well aligned compared to other entries. YAML can be a pain. Sorry about that. If you could properly align it, that would work. Thanks.

**Comment by IndrajeetPatil** [comment]
Does that look better?

image

**Comment by Emaasit** [comment]
Yes. 👍

**Comment by IndrajeetPatil** [comment]
I am still getting an error though (https://github.com/IndrajeetPatil/gallery/branches):
image

I shouldn't create a pull request yet, right?

**Comment by Emaasit** [comment]
You have two duplicate entries of `ggstatsplot`. One of them is causing the error.

**Comment by IndrajeetPatil** [comment]
Oops, sorry about that. I removed the previous, incorrect version from the document, but I still see an error. :(

**Comment by IndrajeetPatil** [comment]
It worked! Will create a pull request now.

image

**Pull request merged**
