### PR TITLE
update `ggstatsplot` counts

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by yutannihilation** [comment]
Sorry, you cannot update this by hand.

**Comment by IndrajeetPatil** [comment]
I am confused. Is this not what you did in this commit https://github.com/ggplot2-exts/gallery/commit/a2173be08393614fc53b1f5233ecdbfe7e1b1e10?

I had also asked if these are updated automatically and was told they are not. So I assumed they need to be changed by hand.
image

**Comment by yutannihilation** [comment]
`github_meta.json` should be updated by `scripts/github_meta.R`.

**Comment by IndrajeetPatil** [comment]
Ah, I see!

**Pull request closed without merging**
