### PR TITLE
ggheatmap

### PR DESCRIPTION
**Pull request by XiaoLuo-boy**

### CODE REVIEW

**Comment by XiaoLuo-boy** [comment]
ggplot2 version of heatmap

**Comment by yutannihilation** [comment]
Thanks!

**Comment by XiaoLuo-boy** [comment]
Dear Hiroaki Yutani
&nbsp; Thank you for your reply!&nbsp;What do I need to do?
Best regards,
XiaoLuo-boy

---Original---
From: "Hiroaki ***@***.***&gt;
Date: Sun, May 23, 2021 21:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ggplot2-exts/gallery] ggheatmap (#122)




 
Thanks!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---Original---
From: "Hiroaki ***@***.***&gt;
Date: Sun, May 23, 2021 21:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ggplot2-exts/gallery] ggheatmap (#122)




 
Thanks!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---Original---
From: "Hiroaki ***@***.***&gt;
Date: Sun, May 23, 2021 21:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ggplot2-exts/gallery] ggheatmap (#122)




 
Thanks!

**Comment by yutannihilation** [comment]
Nothing. As I merged this pull request, ggheatmap is now on <https://exts.ggplot2.tidyverse.org/gallery/> :) Thanks for your contribution!

**Comment by XiaoLuo-boy** [comment]
Thank you for providing us with such an excellent platform


---Original---
From: "Hiroaki ***@***.***&gt;
Date: Sun, May 23, 2021 22:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ggplot2-exts/gallery] ggheatmap (#122)




 
Nothing. As I merged this pull request, ggheatmap is now on https://exts.ggplot2.tidyverse.org/gallery/ :) Thanks for your contribution!

**Pull request merged**
