### PR TITLE
add ggpca

### PR DESCRIPTION
**Pull request by YaoxiangLi**

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
@YaoxiangLi 
Could you make the repository public?

```
*** getting meta data for: YaoxiangLi ggpca
Error in gh("GET /repos/:owner/:repo", owner = wdgt$ghuser, repo = wdgt$ghrepo) : 
  GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/repos/YaoxiangLi/ggpca>
ℹ Read more at <https://docs.github.com/rest/repos/repos#get-a-repository>
```

**Comment by YaoxiangLi** [comment]
@yutannihilation Yes, it should be avaliable now.

**Comment by yutannihilation** [comment]
Thanks!

**Pull request merged**
