### PR TITLE
add survminer to ggplot2-exts

### PR DESCRIPTION
**Pull request by MarcinKosinski**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
@Emaasit could you be so kind and accept this pull request with survminer package : ) ?

**Comment by MarcinKosinski** [comment]
@Emaasit is it possible to have 2 authors?
https://github.com/ggplot2-exts/gallery/blob/gh-pages/_config.yml#L381

Maybe this is the reason we do not appear on your website with survminer http://www.ggplot2-exts.org/gallery/

**Comment by MarcinKosinski** [comment]
@Emaasit should I provide a fix with one author in the configutation (instead of two) to appear on your website?

**Comment by Emaasit** [comment]
@MarcinKosinski I am not certain. Give it a try and let's see what happens.

**Comment by ginolhac** [comment]
would be nice to have this package listed in the extensions. It is a great and useful one

**Comment by MarcinKosinski** [comment]
I removed second author here: https://github.com/ggplot2-exts/gallery/pull/10
Can you be so kind and merge?

**Pull request merged**
