### PR TITLE
Update gganimate

### PR DESCRIPTION
**Pull request by yutannihilation**

### CODE REVIEW

**Comment by yutannihilation** [comment]
@thomasp85 
FYI, I updated the description of gganimate on https://www.ggplot2-exts.org/gallery/. If you find something is wrong, please tell me or update by yourself.

**Comment by thomasp85** [comment]
Thanks @yutannihilation - The extensions page is still using the old version, but I'll update that when I got the time (if you feel like it you are free to do it of course)

**Comment by yutannihilation** [comment]
Oh, I forgot it..., thanks. I'll update briefly for now, please update as you want later!

**Comment by yutannihilation** [comment]
Hmm... Sorry, I tired, but couldn't succeed. It seems harder than I thought to rebuild the site...

**Pull request merged**
