### PR TITLE
Adding the ggjoy package to ggplot2-exts

### PR DESCRIPTION
**Pull request by clauswilke**
I've added the required info for the ggjoy package.

### CODE REVIEW

**Comment by clauswilke** [comment]
Thanks!

**Comment by Emaasit** [comment]
Awesome package BTW. Just used it in my paper and thesis.

**Comment by clauswilke** [comment]
Super!

Btw., does sorting by github star work on the website? ggjoy should be somewhere in the top when sorted by github star, but that doesn't seem to be the case.

**Comment by Emaasit** [comment]
I tried to fix it here https://github.com/ggplot2-exts/gallery/issues/3 but couldn't get it done. Will look at it in detail later.

**Comment by clauswilke** [comment]
A couple of things I noticed:

- Script `scripts/update_meta.sh` tries to `cd` into `$HTMLWIDGET_GALLERY_DIR/htmlwidgetsgallery`. It shouldn't. It should stay in the root directory of the project.

- Script `scripts/github_meta.R` tries to load package `github`, but the package is named `rgithub`.

- Scripts `scripts/github_meta.R` needs an authentication token in stored in `GITHUB_TOKEN`. I have no idea where to get that token, so I couldn't try debug any further.

**Pull request merged**
