### PR TITLE
Add directlabels

### PR DESCRIPTION
**Pull request by Anirban166**
Added [directlabels](https://github.com/tdhock/directlabels) on behalf of @tdhock as per the second objective [here](https://github.com/rstats-gsoc/gsoc2021/wiki/directlabels-improvements#coding-project-directlabels-improvements) (an open-source project!)
Thumbnail taken from https://github.com/tdhock/directlabels/issues/42#issuecomment-869675946

@yutannihilation Can we add multiple links for the 'examples' field?
I went for https://tdhock.github.io/directlabels/docs/index.html which is an example database with links to examples for specific methods, but then there is also a page for several advanced examples: https://tdhock.github.io/directlabels/examples.html
Ideally, it would be nice to have both, but its fine if only one is accepted.

### CODE REVIEW

**Comment by Anirban166** [comment]
The readme mentions 'url or list of urls' so I suppose that is possible (comma-seperated?), but I haven't seen an example yet so wanted to confirm before I break the pattern.

**Comment by tdhock** [comment]
Thanks Anirban

**Comment by Anirban166** [comment]
> Thanks Anirban

Anytime!

**Comment by yutannihilation** [comment]
> Can we add multiple links for the 'examples' field?

Sorry, I don't know. If you want to try, you can add them. In case it won't work, I'll fix it.

**Comment by Anirban166** [comment]
> > Can we add multiple links for the 'examples' field?
> 
> Sorry, I don't know. If you want to try, you can add them. In case it won't work, I'll fix it.

Done, please check!

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
It seems the second one is just ignored.

**Comment by Anirban166** [comment]
Thank you too! 

> It seems the second one is just ignored.

I see, might as well update that on the readme? (like to just use one url)

**Pull request merged**
