### PR TITLE
adds `see` and `ggsignif`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
#121

### CODE REVIEW

**Comment by yutannihilation** [comment]
Thanks! Could you exclude the diffs on .gitignore?

**Comment by yutannihilation** [comment]
Could you remove `.DS_Store`? I recommend you to ignore it globally, btw :)

c.f., https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by IndrajeetPatil** [comment]
But why is updating `.gitignore` to ignore such files not a good solution?

**Comment by yutannihilation** [comment]
Yeah, it's a good idea. I just thought you accidentally included it since these files you listed seemed irrelevant to this project except for `.DS_Store`, sorry. I'll add `.DS_Store` later at least.

**Comment by yutannihilation** [comment]
Thanks!

**Comment by IndrajeetPatil** [comment]
Gotcha! Thanks :)

**Pull request merged**
