### PR TITLE
Trying 1 author in survminer

### PR DESCRIPTION
**Pull request by MarcinKosinski**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
Naah it stil does not appear on http://www.ggplot2-exts.org/gallery/
@Emaasit I think i give up

**Comment by Emaasit** [comment]
I will pull to my local repo & investigate why & try to fix it.

**Comment by Emaasit** [comment]
@MarcinKosinski It now appears on the webite.

**Comment by MarcinKosinski** [comment]
@Emaasit thanks for that. What did you do that it finally appeared? 
Why it didn't appear with my first PR : ) ?

**Comment by Emaasit** [comment]
@MarcinKosinski I am not sure what happened. I checked last night and it had appeared. I didn't even make any modifications. Weird! Anyway try adding the second author back.

**Pull request merged**
